services:
  heatmap:
    image: ghcr.io/simonwehle/activity-heatmap:latest
    container_name: activity-heatmap
    restart: unless-stopped
    environment:
      MAPLIBRE_STYLE: ${MAPLIBRE_STYLE}
    ports:
      - "3465:3465"
    volumes:
      - ./activities:/app/activities
